{{- $hosts := first .Values.ingress.hosts -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-gatekeeper
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
    keycloak-gatekeeper.yaml: |
        # is the url for retrieve the OpenID configuration - normally the <server>/auth/realm/<realm_name>
        discovery-url: {{ .Values.keycloak.discoveryUrl }}
        # the client id for the 'client' application
        client-id: {{ .Values.keycloak.clientId }}
        # the secret associated to the 'client' application
        client-secret: {{ .Values.keycloak.clientSecret }}
        # enforces the cookie to be secure"`
        secure-cookie: false
        # the interface definition you wish the proxy to listen, all interfaces is specified as ':<port>', unix sockets as unix://<REL_PATH>|</ABS PATH>
        listen: :3000
        # whether to enable refresh tokens
        enable-refresh-tokens: true
        # the redirection url, essentially the site url, note: /oauth/callback is added at the end
        redirection-url: http://{{ get $hosts "host"}}
        # the encryption key used to encode the session state
        encryption-key: "{{ randAlphaNum 32 }}"
        # the upstream endpoint which we should proxy request
        upstream-url: http://127.0.0.1:80
